render.yaml
‎services:
‎  - type: web
‎    name: Crypto_Signal_bot.super-pro-tide-bot
‎    env: python
‎    plan: free
‎    buildCommand: "pip install -r requirements.txt"
‎    startCommand: "python3
